// this code is autogenerated, do not check it into to your code repository

// ref lib/zixir/engine/math.ex:11
/// Sum of f64 list. BEAM allocator used if Zig allocates.
pub fn list_sum(array: []const f64) f64 {
  var sum: f64 = 0.0;
  for (array) |item| {
    sum += item;
  }
  return sum;
}

/// Product of f64 list.
pub fn list_product(array: []const f64) f64 {
  var prod: f64 = 1.0;
  for (array) |item| {
    prod *= item;
  }
  return prod;
}

/// Dot product of two f64 slices. Returns 0.0 if lengths differ.
pub fn dot_product(a: []const f64, b: []const f64) f64 {
  if (a.len != b.len) return 0.0;
  var sum: f64 = 0.0;
  for (a, b) |x, y| {
    sum += x * y;
  }
  return sum;
}

/// Byte length of binary. No allocation.
pub fn string_count(string: []const u8) i64 {
  return @intCast(string.len);
}
